export const USER_ADD_BAG_REQUEST = 'USER_ADD_BAG_REQUEST'
export const USER_ADD_BAG_SUCCESS = 'USER_ADD_BAG_SUCCESS'
export const USER_ADD_BAG_FAIL = 'USER_ADD_BAG_FAIL'

export const USER_DELETE_BAG_REQUEST = 'USER_DELETE_BAG_REQUEST'
export const USER_DELETE_BAG_SUCCESS = 'USER_DELETE_BAG_SUCCESS'
export const USER_DELETE_BAG_FAIL = 'USER_DELETE_BAG_FAIL'

export const USER_CALL_BAG_REQUEST = 'USER_CALL_BAG_REQUEST'
export const USER_CALL_BAG_SUCCESS = 'USER_CALL_BAG_SUCCESS'
export const USER_CALL_BAG_FAIL = 'USER_CALL_BAG_FAIL'