export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DUPLICATE_USERNAME_REQUEST = 'USER_DUPLICATE_USERNAME_REQUEST'
export const USER_DUPLICATE_USERNAME_SUCCESS = 'USER_DUPLICATE_USERNAME_SUCCESS'
export const USER_DUPLICATE_USERNAME_FAIL = 'USER_DUPLICATE_USERNAME_FAIL'

export const USER_DUPLICATE_EMAIL_REQUEST = 'USER_DUPLICATE_EMAIL_REQUEST'
export const USER_DUPLICATE_EMAIL_SUCCESS = 'USER_DUPLICATE_EMAIL_SUCCESS'
export const USER_DUPLICATE_EMAIL_FAIL = 'USER_DUPLICATE_EMAIL_FAIL'

export const USER_RESET_EMAIL_DUPLICATE_CHECK = 'USER_RESET_EMAIL_DUPLICATE_CHECK'
export const USER_RESET_USERNAME_DUPLICATE_CHECK = 'USER_RESET_USERNAME_DUPLICATE_CHECK'

export const USER_ERROR_SUCCESS_RESET = 'USER_ERROR_SUCCESS_RESET'


export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST'
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS'
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL'

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST'
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS'
export const USER_INFO_FAIL = 'USER_INFO_FAIL'

export const USER_INFO_UPDATE_REQUEST = 'USER_INFO_UPDATE_REQUEST'
export const USER_INFO_UPDATE_SUCCESS = 'USER_INFO_UPDATE_SUCCESS'
export const USER_INFO_UPDATE_FAIL = 'USER_INFO_UPDATE_FAIL'

export const USER_INBODY_REQUEST = 'USER_INBODY_REQUEST'
export const USER_INBODY_SUCCESS = 'USER_INBODY_SUCCESS'
export const USER_INBODY_FAIL = 'USER_INBODY_FAIL'

export const USER_INBODY_UPDATE_REQUEST = 'USER_INBODY_UPDATE_REQUEST'
export const USER_INBODY_UPDATE_SUCCESS = 'USER_INBODY_UPDATE_SUCCESS'
export const USER_INBODY_UPDATE_FAIL = 'USER_INBODY_UPDATE_FAIL'