export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_DUPLICATE_USERNAME_REQUEST = 'USER_DUPLICATE_USERNAME_REQUEST'
export const USER_DUPLICATE_USERNAME_SUCCESS = 'USER_DUPLICATE_USERNAME_SUCCESS'
export const USER_DUPLICATE_USERNAME_FAIL = 'USER_DUPLICATE_USERNAME_FAIL'

export const USER_DUPLICATE_EMAIL_REQUEST = 'USER_DUPLICATE_EMAIL_REQUEST'
export const USER_DUPLICATE_EMAIL_SUCCESS = 'USER_DUPLICATE_EMAIL_SUCCESS'
export const USER_DUPLICATE_EMAIL_FAIL = 'USER_DUPLICATE_EMAIL_FAIL'

export const USER_RESET_EMAIL_DUPLICATE_CHECK = 'USER_RESET_EMAIL_DUPLICATE_CHECK'
export const USER_RESET_USERNAME_DUPLICATE_CHECK = 'USER_RESET_USERNAME_DUPLICATE_CHECK'

export const USER_ERROR_SUCCESS_RESET = 'USER_ERROR_SUCCESS_RESET'